[user]
name = "Robert Stefanic"
email = "rstefanic72@gmail.com"

[ui]
editor = "nvim"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[aliases]
l = ["log", "-s", "-T", "description"]

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.summary(),
  "\n\n",
  diff.git()
)
'''
