[user]
name = "Robert Stefanic"
email = "rstefanic72@gmail.com"

[ui]
editor = "nvim"
default-command = "log"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519.pub"
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"

[aliases]
l = ["log", "-s", "-T", "description"]
nb = ["new", "-B", "@", "--no-edit"]
si = ["squash", "-i"]
pe = ["prev", "--edit"]
ne = ["next", "--edit"]
# Copied from Thorsten Ball: https://github.com/mrnugget/dotfiles/blob/0a943f0e8b9907f7f6712ac11156a00d4634a3e5/jj_config.toml#L8-L9
tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]

[revset-aliases]
"closest_bookmark(to)" = "heads(::to & bookmarks())"

[templates]
draft_commit_description = '''
concat(
  coalesce(description, default_commit_description, "\n"),
  surround(
    "\nJJ: This commit contains the following changes:\n", "",
    indent("JJ:     ", diff.stat(72)),
  ),
  "\nJJ: ignore-rest\n",
  diff.summary(),
  "\n\n",
  diff.git()
)
'''
